In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import classification_report, accuracy_score
from sklearn.model_selection import train_test_split
import re
import string
print("All imports successful!")

All imports successful!

In [4]:
import pandas as pd

data_fake = pd.read_csv(r'C:\Users\Acer\Downloads\Fake.csv')
data_true = pd.read_csv(r'C:\Users\Acer\Downloads\true.csv')

In [5]:
data_fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [6]:
data_true.head()

,title,text,subject
0,"Self-immolation cases rising, Odisha govt tell...","Self-immolation cases rising, Odisha govt tell...",India
1,‘Attempt to discredit’: After Air India flight...,‘Attempt to discredit’: After Air India flight...,India
2,Nagpur slaughterhouses and meat shops to remai...,Nagpur slaughterhouses and meat shops to remai...,India
3,‘No coercive steps to be taken’: SC respite fo...,‘No coercive steps to be taken’: SC respite fo...,India
4,Kerala man’s Grindr encounter ends in gold rob...,Kerala man’s Grindr encounter ends in gold rob...,India

In [7]:
data_fake["class"] = 0
data_true['class'] = 1

In [8]:
data_fake.shape, data_true.shape

((23481, 5), (24485, 4))

In [9]:
data_fake_manual_testing = data_fake.tail(10)
for i in range(23481,  23485, -1):
    data_fake.drop([i], axis = 0, inplace = True)


data_true_manual_testing = data_true.tail(10)
for i in range(21416,  21406, -1):
    data_true.drop([i], axis = 0, inplace = True)

In [10]:
data_fake.shape,data_true.shape

((23481, 5), (24475, 4))

In [11]:
data_fake_manual_testing.head(10)

,title,text,subject,date,class
23471,Seven Iranians freed in the prisoner swap have...,"21st Century Wire says This week, the historic...",Middle-east,"January 20, 2016",0
23472,#Hashtag Hell & The Fake Left,By Dady Chery and Gilbert MercierAll writers ...,Middle-east,"January 19, 2016",0
23473,Astroturfing: Journalist Reveals Brainwashing ...,Vic Bishop Waking TimesOur reality is carefull...,Middle-east,"January 19, 2016",0
23474,The New American Century: An Era of Fraud,Paul Craig RobertsIn the last years of the 20t...,Middle-east,"January 19, 2016",0
23475,Hillary Clinton: ‘Israel First’ (and no peace ...,Robert Fantina CounterpunchAlthough the United...,Middle-east,"January 18, 2016",0
23476,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016",0
23477,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016",0
23478,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016",0
23479,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016",0
23480,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016",0

In [22]:
data_true_manual_testing.head(10)

,title,text,subject,class
24475,Highlight of interim budget is emphasis on cap...,Highlight of interim budget is emphasis on cap...,Business,1
24476,"In a boost to ‘Make in India’ initiative, Indi...","In a boost to ‘Make in India’ initiative, Indi...",Business,1
24477,Show sensitivity to exporters in view of Red S...,Show sensitivity to exporters in view of Red S...,Business,1
24478,India’s fuel consumption rises 8% year-on-year...,India’s fuel consumption rises 8% year-on-year...,Business,1
24479,RBI says clampdown on Paytm Payments Bank due ...,RBI says clampdown on Paytm Payments Bank due ...,Business,1
24480,"RBI leaves repo rate unchanged, food inflation...","RBI leaves repo rate unchanged, food inflation...",Business,1
24481,"Stock Market Today: Sensex, Nifty dips near 1%...","Stock Market Today: Sensex, Nifty dips near 1%...",Business,1
24482,RBI Monetary Policy Meeting Highlights: Shakti...,RBI Monetary Policy Meeting Highlights: Shakti...,Business,1
24483,Govt urges RBI to issue FAQs for Paytm users,Govt urges RBI to issue FAQs for Paytm users,Business,1
24484,"‘WTO not place for discussing labour, environm...","‘WTO not place for discussing labour, environm...",Business,1

In [12]:
data_merge = pd.concat([data_fake,data_true], axis = 0)
data_merge.head(10)

,title,text,subject,date,class
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0
5,Racist Alabama Cops Brutalize Black Boy While...,The number of cases of cops brutalizing and ki...,News,"December 25, 2017",0
6,"Fresh Off The Golf Course, Trump Lashes Out A...",Donald Trump spent a good portion of his day a...,News,"December 23, 2017",0
7,Trump Said Some INSANELY Racist Stuff Inside ...,In the wake of yet another court decision that...,News,"December 23, 2017",0
8,Former CIA Director Slams Trump Over UN Bully...,Many people have raised the alarm regarding th...,News,"December 22, 2017",0
9,WATCH: Brand-New Pro-Trump Ad Features So Muc...,Just when you might have thought we d get a br...,News,"December 21, 2017",0

In [13]:
data_merge.columns

Index(['title', 'text', 'subject', 'date', 'class'], dtype='str')

In [14]:
data = data_merge.drop(['title','subject','date'],axis = 1)

In [15]:
data.isnull().sum()

text     5
class    0
dtype: int64

In [16]:
data['text'] = data['text'].fillna('0')

data.isnull().sum()

text     0
class    0
dtype: int64

In [17]:
data = data.sample(frac= 1)

In [18]:
data.head()

                                                   text  class
8134  Reports out of Texas are saying that Supreme C...      0
8966  All new Abhay Singh loses final but ‘enjoying ...      1
3616  India and Pakistan will figure it out ‘one way...      1
3096  Operation Sindoor: Army mobilises additional f...      1
2911  We ll likely never know exactly how many peopl...      0

In [19]:
data.reset_index(inplace = True)
data.drop(['index'],axis =1, inplace = True)

In [20]:
data.columns

Index(['text', 'class'], dtype='str')

In [21]:
data.head()

                                                text  class
0  Reports out of Texas are saying that Supreme C...      0
1  All new Abhay Singh loses final but ‘enjoying ...      1
2  India and Pakistan will figure it out ‘one way...      1
3  Operation Sindoor: Army mobilises additional f...      1
4  We ll likely never know exactly how many peopl...      0

In [22]:
import re
import string

def wordopt(text):
    text = str(text)
    text = text.lower()
    text = re.sub(r'\[.*?\]', '', text)
    text = re.sub(r'https?://\S+|www\.\S+', '', text)
    text = re.sub(r'<.*?>', '', text)
    text = re.sub(r'\b\w*\d\w*\b', '', text)
    text = re.sub(r'[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

In [23]:
data['text'] = data['text'].apply(wordopt)

In [24]:
x = data['text']
y = data['class']

In [25]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.25)

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorization = TfidfVectorizer()
xv_train = vectorization.fit_transform(x_train)
xv_test = vectorization.transform(x_test)

In [27]:
from sklearn.linear_model import LogisticRegression

LR = LogisticRegression()
LR.fit(xv_train, y_train)

LogisticRegression()

In [29]:
pred_lr = LR.predict(xv_test)

In [30]:
LR.score(xv_test, y_test)

0.9775627658687129

In [31]:
print(classification_report(y_test, pred_lr))

              precision    recall  f1-score   support

           0       0.99      0.96      0.98      5869
           1       0.96      1.00      0.98      6120

    accuracy                           0.98     11989
   macro avg       0.98      0.98      0.98     11989
weighted avg       0.98      0.98      0.98     11989

In [32]:
from sklearn.tree import DecisionTreeClassifier
DT =  DecisionTreeClassifier()
DT.fit(xv_train, y_train)

DecisionTreeClassifier()

In [33]:
pred_dt = DT.predict(xv_test)

In [34]:
DT.score(xv_test,y_test)

0.9841521394611727

In [35]:
print(classification_report(y_test, pred_dt))

              precision    recall  f1-score   support

           0       0.98      0.99      0.98      5869
           1       0.99      0.98      0.98      6120

    accuracy                           0.98     11989
   macro avg       0.98      0.98      0.98     11989
weighted avg       0.98      0.98      0.98     11989

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
GB = GradientBoostingClassifier(random_state = 0)
GB.fit(xv_train, y_train)

In [54]:
pred_gb = GB.predict(xv_test)

In [55]:
GB.score(xv_test, y_test)

0.9731420468763032

In [42]:
print(classification_report(y_test, pred_gb))

              precision    recall  f1-score   support

           0       0.99      0.95      0.97      5869
           1       0.96      0.99      0.97      6120

    accuracy                           0.97     11989
   macro avg       0.97      0.97      0.97     11989
weighted avg       0.97      0.97      0.97     11989

In [43]:
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(random_state = 0)
RF.fit(xv_train, y_train)

RandomForestClassifier(random_state=0)

In [44]:
pred_rf = RF.predict(xv_test)

In [45]:
RF.score(xv_test, y_test)

0.9895737759612978

In [46]:
print(classification_report(y_test, pred_rf))

              precision    recall  f1-score   support

           0       1.00      0.98      0.99      5869
           1       0.98      1.00      0.99      6120

    accuracy                           0.99     11989
   macro avg       0.99      0.99      0.99     11989
weighted avg       0.99      0.99      0.99     11989

In [62]:
# def output_lable(n):
#     if n == 0:
#         return "Fake News"
#     elif n == 1:
#         return "Not A Fake News"


# def manual_testing(news):
#     testing_news = {"text": [news]}
#     new_def_test = pd.DataFrame(testing_news)

#     new_def_test["text"] = new_def_test["text"].apply(wordopt)

#     new_x_test = new_def_test["text"]
#     new_xv_test = vectorization.transform(new_x_test)

#     pred_LR = LR.predict(new_xv_test)
#     pred_DT = DT.predict(new_xv_test)
#     pred_GB = GB.predict(new_xv_test)
#     pred_RF = RF.predict(new_xv_test)

#     return print(
#         "\n\nLR Prediction: {}\nDT Prediction: {}\nGB Prediction: {}\nRF Prediction: {}".format(
#             output_lable(pred_LR[0]),
#             output_lable(pred_DT[0]),
#             output_lable(pred_GB[0]),
#             output_lable(pred_RF[0])
#         )
#     )

In [66]:
def manual_testing(news):

    testing_news = {"text": [news]}
    new_df = pd.DataFrame(testing_news)

    new_x = new_df["text"]
    new_x = vectorization.transform(new_x)

    pred_LR = LR.predict(new_x)
    pred_DT = DT.predict(new_x)
    pred_GB = GB.predict(new_x)
    pred_RF = RF.predict(new_x)

    lr_result = output_label(pred_LR[0])
    dt_result = output_label(pred_DT[0])
    gb_result = output_label(pred_GB[0])
    rf_result = output_label(pred_RF[0])

    print("LR Prediction:", lr_result)
    print("DT Prediction:", dt_result)
    print("GB Prediction:", gb_result)
    print("RF Prediction:", rf_result)

    predictions = [lr_result, dt_result, gb_result, rf_result]

    fake_count = predictions.count("Fake News")
    real_count = predictions.count("Not A Fake News")

    if fake_count > real_count:
        final_prediction = "Fake News"
    else:
        final_prediction = "Not A Fake News"

    print("\nFinal Prediction:", final_prediction)

In [68]:
def output_label(n):
    if n == 0:
        return "Fake News"
    elif n == 1:
        return "Not A Fake News"

In [69]:
news = str(input())
manual_testing(news)

 BREAKING NEWS: Bengaluru Metro to Offer Free Travel for All Passengers from November 1  Bengaluru, October 22, 2026 — A fictional announcement claims that Bengaluru Metro will provide completely free travel to all passengers starting November 1, 2026. The announcement says the initiative is being introduced to reduce traffic and encourage public transport.  Note: This is a fictional/fake news example created only for practice and educational purposes. It is not a real announcement.

LR Prediction: Fake News
DT Prediction: Fake News
GB Prediction: Fake News
RF Prediction: Not A Fake News

Final Prediction: Fake News

In [70]:
news = str(input())
manual_testing(news)

 The Reserve Bank of India is the central bank of India and is responsible for monetary policy.

LR Prediction: Not A Fake News
DT Prediction: Not A Fake News
GB Prediction: Not A Fake News
RF Prediction: Not A Fake News

Final Prediction: Not A Fake News